### ISSUE TITLE
Sprockets::FileNotFound: couldn't find file 'bootstrap'

### ISSUE THREAD

**Issue by reasonpun** [fxhover/blog#1]
Hi,~~
 i did this
"cell:/blog$RAILS_ENV=production bundle exec rake assets:precompile" 
then show message below:
# 

rake aborted!
Sprockets::FileNotFound: couldn't find file 'bootstrap'
  (in /blog/app/assets/stylesheets/application.css:15)

Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
# 

can u help me, what's the matter about this? thx very much!

**Comment by fxhover** [comment]
change Gemfile:
gem 'bootstrap-sass' 
to: gem 'bootstrap-sass', '~>  3.2.0.1'

try:
RAILS_ENV=production bundle exec bundle install
RAILS_ENV=production bundle exec rake assets:precompile

**Comment by reasonpun** [comment]
ok,thank u very much, I will try it.
