### ISSUE TITLE
密码错误

### ISSUE THREAD

**Issue by guoyoujin** [fxhover/blog#2]
我使用admin登陆为什么她老是提示密码错误呢

**Comment by fxhover** [comment]
输入的不正确吧，默认的用户名密码：admin   adminqwe

**Comment by guoyoujin** [comment]
没有啊，是正确的啊我都在后台打印了，我知道那个配置数据库文件在哪里

**Comment by guoyoujin** [comment]
@fxhover 没有啊，是正确的啊我都在后台打印了，我知道那个配置数据库文件在哪里

**Comment by guoyoujin** [comment]
@fxhover 
def login_confirm
    puts "=====================#{params[:user][:username]}========"
    puts "=====================#{params[:user][:password]}========"
    @user = User.find_by username: params[:user][:username]
    unless @user.activation?
      session[:wait_active_email] = @user.email
      flash.now[:error] = "用户还没有激活，<a href='#{send_active_mail_users_path}'>点此</a>发送激活邮件。"
      return render 'login', layout: 'register'
    end
    if @user && @user.check_password(params[:user][:password])
      to_login @user
      @user.update_attribute :last_login_time, DateTime.now
      redirect_to (params[:from].present? ? params[:from] : root_path)
    else
      flash[:error] = '用户名或密码错误'
      render 'login', layout: 'register'
    end
  rescue
    flash[:error] = '用户名或密码错误'
    render 'login', layout: 'register'
  end

**Comment by guoyoujin** [comment]
@fxhover ，还想问下请问你这个发送邮件是怎么配置的啊，我这边一直没收到邮件

**Comment by fxhover** [comment]
邮件的配置在：config/blog.yml中，mailer项，配置好邮件服务器地址，发送账户和密码，如果确定这些都配置正确还是发不了邮件的话，看看config/application.rb中的：config.action_mailer.smtp_settings，把authentication项改成其他值试试。

**Comment by guoyoujin** [comment]
@fxhover 好的谢谢啦
