### ISSUE TITLE
数据库查询问题

### ISSUE THREAD

**Issue by guoyoujin** [fxhover/blog#3]
当我把他部署到服务器后，不知掉为什么只要涉足到中文，程序就会报错，但是在本地就不会出问题，这是为什么啊啊

**Comment by guoyoujin** [comment]
[2015-07-22T16:40:42.263780 #15839]  INFO -- : Processing by ArticlesController#index as HTML
I, [2015-07-22T16:40:42.263929 #15839]  INFO -- :   Parameters: {"utf8"=>"✓", "keyword"=>"诶哦"}
D, [2015-07-22T16:40:42.265727 #15839] DEBUG -- :   User Load (0.2ms)  SELECT  `users`.\* FROM `users`  WHERE `users`.`id` = 1 LIMIT 1
D, [2015-07-22T16:40:42.269252 #15839] DEBUG -- :   Article Load (0.6ms)  SELECT  `articles`.\* FROM `articles`  WHERE (title like '%诶哦%')  ORDER BY updated_at desc LIMIT 10 OFFSET 0
E, [2015-07-22T16:40:42.269429 #15839] ERROR -- : Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'like': SELECT  `articles`.\* FROM `articles`  WHERE (title like '%诶哦%')  ORDER BY updated_at desc LIMIT 10 OFFSET 0
I, [2015-07-22T16:40:42.270311 #15839]  INFO -- :   Rendered articles/_articles.html.haml (2.0ms)
I, [2015-07-22T16:40:42.270494 #15839]  INFO -- :   Rendered articles/index.html.haml within layouts/application (3.5ms)
I, [2015-07-22T16:40:42.270989 #15839]  INFO -- :   Rendered public/500.html (0.0ms)
I, [2015-07-22T16:40:42.271235 #15839]  INFO -- : Completed 500 Internal Server Error in 7ms (Views: 0.4ms | ActiveRecord: 0.8ms)

**Comment by fxhover** [comment]
@guoyoujin  应该是数据库编码的问题，参考：http://stackoverflow.com/questions/1008287/illegal-mix-of-collations-mysql-error

**Comment by guoyoujin** [comment]
@fxhover 你能出一个自动化部署版本吗，我使用自动化（capistrano）老是部署不成功
