### ISSUE TITLE
头像无法上传

### ISSUE THREAD

**Issue by wxy1106** [fxhover/blog#5]
你好，我用你的源码搭了博客，发现设置里头像无法上传，不管是png还是jpg格式点修改按钮都会提示“不是图片格式”，请问是什么问题，应该如何解决呢？谢谢

![qq 20160713095449](https://cloud.githubusercontent.com/assets/18569573/16789403/e00e99b2-48df-11e6-9847-f5f404e62d19.png)

**Comment by wxy1106** [comment]
确定格式是正确的

![qq 20160713095449](https://cloud.githubusercontent.com/assets/18569573/16789422/09dbce90-48e0-11e6-922c-a4c1f9ac808a.png)

**Comment by fxhover** [comment]
@wxy1106 图片上传判断类型使用的linux的file命令，请问你用的是什么系统？
file --mime -b upload_file.xx

**Comment by wxy1106** [comment]
@fxhover 原来如此，是系统没装file这软件，不识别file命令。
装完上传就正常了，非常感谢~
